"""init

Revision ID: 7d31fd3dfb9d
Revises: 
Create Date: 2022-03-28 14:38:19.903451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d31fd3dfb9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_notes',
    sa.Column('id', sa.String(), autoincrement=True, nullable=False),
    sa.Column('qr', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_notes_id'), 'qr_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_notes_id'), table_name='qr_notes')
    op.drop_table('qr_notes')
    # ### end Alembic commands ###
